#!/usr/bin/env python3
"""Build static HTML storybook pages from markdown content."""

from __future__ import annotations

import argparse
from pathlib import Path

from storybook_tools import parse_scenes, render_html, write_html


PROJECT = Path(__file__).resolve().parents[1]


ZH_DEFAULTS = {
    "language": "zh-Hans",
    "book_title": "佛陀的一生",
    "page_title": "佛陀的一生 - 图像故事书",
    "scene_label": "第",
    "scene_suffix": "幕",
    "scene_select_label": "场景",
    "previous_label": "← 上一幕",
    "next_label": "下一幕 →",
    "play_label": "▶ 播放",
    "pause_label": "⏸ 暂停",
    "continuous_label": "连续播放",
    "beginning_label": "开始",
    "progress_end_label": "觉悟之路展开",
    "asset_prefix": "../",
    "audio_dir": "../assets/audio/zh",
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--language", choices=["zh"], default="zh")
    parser.add_argument(
        "--source",
        type=Path,
        default=PROJECT / "content/the-life-of-the-buddha-picture-storybook.zh.md",
    )
    parser.add_argument("--output", type=Path, default=PROJECT / "cn/index.html")
    args = parser.parse_args()

    if args.language != "zh":
        raise RuntimeError("Only the Chinese page is generated by this script for now.")

    scenes = parse_scenes(args.source, args.language)
    html = render_html(scenes=scenes, **ZH_DEFAULTS)
    write_html(args.output, html)
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
